/** 编辑器操作文案随产品语言切换；AMC 原始字段名称保持格式原文。 */
import { usePreferencesStore } from '@/stores/usePreferencesStore';
import { useCallback } from 'react';

const rows: Record<string, [string, string, string, string]> = {
  隐藏选中组件: [
    'Hide selected component',
    'Ausgewählte Komponente ausblenden',
    'Masquer le composant sélectionné',
    'Nascondi componente selezionato',
  ],
  显示全部组件: [
    'Show all components',
    'Alle Komponenten anzeigen',
    'Afficher tous les composants',
    'Mostra tutti i componenti',
  ],
  '下载装配 GLB': [
    'Download assembly GLB',
    'Montage-GLB herunterladen',
    'Télécharger l’assemblage GLB',
    'Scarica assemblaggio GLB',
  ],
  '下载包含预览挂载；发布保留基体与挂点，详情页可自由装配。': [
    'Downloads include preview attachments. Published models keep the base and sockets for assembly in details.',
    'Downloads enthalten die Vorschau-Anbauteile. Veröffentlichte Modelle behalten Basis und Befestigungspunkte zur Montage in den Details.',
    'Les téléchargements incluent les accessoires de l’aperçu. Les modèles publiés conservent la base et les fixations pour assemblage dans les détails.',
    'I download includono i componenti in anteprima. I modelli pubblicati conservano base e agganci per l’assemblaggio nei dettagli.',
  ],
  新建三维设计: [
    'New 3D design',
    'Neuer 3D-Entwurf',
    'Nouvelle conception 3D',
    'Nuovo progetto 3D',
  ],
  航空器: ['Aircraft', 'Luftfahrzeug', 'Aéronef', 'Aeromobile'],
  外挂部件: ['Attachment', 'Anbauteil', 'Accessoire', 'Componente'],
  操作失败: [
    'Operation failed',
    'Vorgang fehlgeschlagen',
    'Échec de l’opération',
    'Operazione non riuscita',
  ],
  模型需要先入库: [
    'Import the model into the library first',
    'Modell zuerst importieren',
    'Importez d’abord le modèle',
    'Importare prima il modello',
  ],
  ' 副本': [' copy', ' Kopie', ' copie', ' copia'],
  副本: ['Copy', 'Kopie', 'Copie', 'Copia'],
  ' 自定义': [' custom', ' angepasst', ' personnalisé', ' personalizzato'],
  '正在更新三维预览…': [
    'Updating 3D preview…',
    '3D-Vorschau wird aktualisiert…',
    'Actualisation de l’aperçu 3D…',
    'Aggiornamento anteprima 3D…',
  ],
  三维预览已更新: [
    '3D preview updated',
    '3D-Vorschau aktualisiert',
    'Aperçu 3D actualisé',
    'Anteprima 3D aggiornata',
  ],
  保留上一次有效预览: [
    'Showing the last valid preview',
    'Letzte gültige Vorschau',
    'Dernier aperçu valide conservé',
    'Ultima anteprima valida conservata',
  ],
  组件名称已存在: [
    'Component name already exists',
    'Komponentenname bereits vorhanden',
    'Nom de composant déjà utilisé',
    'Nome componente già presente',
  ],
  新挂点: [
    'New socket',
    'Neuer Befestigungspunkt',
    'Nouveau point de fixation',
    'Nuovo punto di aggancio',
  ],
  安装锚点: ['Attachment anchor', 'Montageanker', 'Ancre de montage', 'Ancora di montaggio'],
  'AFSIM Mover Creator · 三维建模': [
    'AFSIM Mover Creator · 3D design',
    'AFSIM Mover Creator · 3D-Modellierung',
    'AFSIM Mover Creator · Modélisation 3D',
    'AFSIM Mover Creator · Modellazione 3D',
  ],
  关闭编辑器: ['Close editor', 'Editor schließen', 'Fermer l’éditeur', 'Chiudi editor'],
  设计名称: ['Design name', 'Entwurfsname', 'Nom de la conception', 'Nome progetto'],
  版本: ['Version', 'Version', 'Version', 'Versione'],
  新设计: ['New design', 'Neuer Entwurf', 'Nouvelle conception', 'Nuovo progetto'],
  ' · 未保存': [' · Unsaved', ' · Ungespeichert', ' · Non enregistré', ' · Non salvato'],
  撤销: ['Undo', 'Rückgängig', 'Annuler', 'Annulla'],
  重做: ['Redo', 'Wiederholen', 'Rétablir', 'Ripeti'],
  保存版本: ['Save version', 'Version speichern', 'Enregistrer la version', 'Salva versione'],
  已保存版本: ['Saved version', 'Gespeicherte Version', 'Version enregistrée', 'Versione salvata'],
  另存副本: ['Save a copy', 'Kopie speichern', 'Enregistrer une copie', 'Salva copia'],
  模型分类: ['Model category', 'Modellkategorie', 'Catégorie du modèle', 'Categoria modello'],
  发布到模型库: [
    'Publish to model library',
    'In Modellbibliothek veröffentlichen',
    'Publier dans la bibliothèque',
    'Pubblica nella libreria',
  ],
  '当前修改尚未保存，刷新恢复草稿已保留。': [
    'Changes are unsaved. A recovery draft is available.',
    'Änderungen ungespeichert. Ein Entwurf zur Wiederherstellung ist vorhanden.',
    'Modifications non enregistrées. Un brouillon de récupération est disponible.',
    'Modifiche non salvate. È disponibile una bozza di recupero.',
  ],
  保存后关闭: [
    'Save and close',
    'Speichern und schließen',
    'Enregistrer et fermer',
    'Salva e chiudi',
  ],
  关闭并保留草稿: [
    'Close and keep draft',
    'Schließen und Entwurf behalten',
    'Fermer et conserver le brouillon',
    'Chiudi e conserva bozza',
  ],
  继续编辑: [
    'Continue editing',
    'Weiter bearbeiten',
    'Continuer la modification',
    'Continua modifica',
  ],
  '发现未保存的三维草稿：': [
    'Unsaved 3D draft: ',
    'Ungespeicherter 3D-Entwurf: ',
    'Brouillon 3D non enregistré : ',
    'Bozza 3D non salvata: ',
  ],
  恢复草稿: [
    'Restore draft',
    'Entwurf wiederherstellen',
    'Restaurer le brouillon',
    'Ripristina bozza',
  ],
  忽略提示: ['Dismiss', 'Ausblenden', 'Ignorer', 'Ignora'],
  '内置模板 ·': [
    'Built-in templates ·',
    'Integrierte Vorlagen ·',
    'Modèles intégrés ·',
    'Modelli integrati ·',
  ],
  搜索三维模板: [
    'Search 3D templates',
    '3D-Vorlagen suchen',
    'Rechercher les modèles 3D',
    'Cerca modelli 3D',
  ],
  搜索模板名称: [
    'Search template name',
    'Vorlagenname suchen',
    'Rechercher un nom de modèle',
    'Cerca nome modello',
  ],
  '个发动机 ·': ['engines ·', 'Triebwerke ·', 'moteurs ·', 'motori ·'],
  份翼型数据: [
    'airfoil datasets',
    'Profil-Datensätze',
    'jeux de données de profil',
    'serie di dati dei profili',
  ],
  '导入 AMC / 依赖 ZIP / GLB': [
    'Import AMC / dependency ZIP / GLB',
    'AMC / Abhängigkeits-ZIP / GLB importieren',
    'Importer AMC / ZIP de dépendances / GLB',
    'Importa AMC / ZIP dipendenze / GLB',
  ],
  导入三维设计: [
    'Import 3D design',
    '3D-Entwurf importieren',
    'Importer une conception 3D',
    'Importa progetto 3D',
  ],
  空白设计: ['Blank design', 'Leerer Entwurf', 'Conception vierge', 'Progetto vuoto'],
  已保存设计: [
    'Saved designs',
    'Gespeicherte Entwürfe',
    'Conceptions enregistrées',
    'Progetti salvati',
  ],
  打开已保存设计: [
    'Open saved design',
    'Gespeicherten Entwurf öffnen',
    'Ouvrir une conception enregistrée',
    'Apri progetto salvato',
  ],
  选择设计: ['Choose design', 'Entwurf wählen', 'Choisir une conception', 'Scegli progetto'],
  设计历史版本: [
    'Design version history',
    'Entwurfsversionen',
    'Historique des versions',
    'Cronologia versioni',
  ],
  历史版本: [
    'Version history',
    'Versionsverlauf',
    'Historique des versions',
    'Cronologia versioni',
  ],
  '历史参数已恢复到草稿，保存会创建新版本': [
    'Historical parameters restored to draft; saving creates a new version',
    'Historische Parameter wiederhergestellt; Speichern erstellt eine neue Version',
    'Paramètres historiques restaurés ; l’enregistrement crée une nouvelle version',
    'Parametri storici ripristinati; il salvataggio crea una nuova versione',
  ],
  恢复历史参数: [
    'Restore historical parameters',
    'Historische Parameter wiederherstellen',
    'Restaurer les paramètres historiques',
    'Ripristina parametri storici',
  ],
  整机: ['Whole model', 'Gesamtmodell', 'Modèle entier', 'Modello intero'],
  线框: ['Wireframe', 'Drahtgitter', 'Fil de fer', 'Reticolo'],
  适应窗口: ['Fit to view', 'Ansicht anpassen', 'Ajuster à la vue', 'Adatta alla vista'],
  俯视: ['Top', 'Oben', 'Dessus', 'Dall’alto'],
  侧视: ['Side', 'Seite', 'Côté', 'Laterale'],
  正视: ['Front', 'Vorne', 'Face', 'Frontale'],
  重新生成预览: [
    'Regenerate preview',
    'Vorschau neu erzeugen',
    'Régénérer l’aperçu',
    'Rigenera anteprima',
  ],
  'AMC：X 前 / Y 右 / Z 下，英尺、度。挂点：X 前 / Y 上 / Z 右，米、度。': [
    'AMC: X forward / Y right / Z down, feet and degrees. Sockets: X forward / Y up / Z right, meters and degrees.',
    'AMC: X vor / Y rechts / Z ab, Fuß und Grad. Befestigung: X vor / Y auf / Z rechts, Meter und Grad.',
    'AMC : X avant / Y droite / Z bas, pieds et degrés. Fixations : X avant / Y haut / Z droite, mètres et degrés.',
    'AMC: X avanti / Y destra / Z giù, piedi e gradi. Agganci: X avanti / Y su / Z destra, metri e gradi.',
  ],
  '下载 GLB': ['Download GLB', 'GLB herunterladen', 'Télécharger GLB', 'Scarica GLB'],
  '下载 AMC 与依赖': [
    'Download AMC and dependencies',
    'AMC und Abhängigkeiten herunterladen',
    'Télécharger AMC et dépendances',
    'Scarica AMC e dipendenze',
  ],
  '发布：': ['Publishing: ', 'Veröffentlichung: ', 'Publication : ', 'Pubblicazione: '],
  排队中: ['Queued', 'In Warteschlange', 'En attente', 'In coda'],
  生成中: ['Generating', 'Wird erzeugt', 'Génération', 'Generazione'],
  已进入模型库: [
    'Added to model library',
    'In Modellbibliothek aufgenommen',
    'Ajouté à la bibliothèque',
    'Aggiunto alla libreria',
  ],
  失败: ['Failed', 'Fehlgeschlagen', 'Échec', 'Non riuscito'],
  重试发布: [
    'Retry publishing',
    'Erneut veröffentlichen',
    'Réessayer la publication',
    'Riprova pubblicazione',
  ],
  组件与挂点: [
    'Components and sockets',
    'Komponenten und Befestigungspunkte',
    'Composants et fixations',
    'Componenti e agganci',
  ],
  组件实例: [
    'Component instance',
    'Komponenteninstanz',
    'Instance de composant',
    'Istanza componente',
  ],
  新增组件类型: [
    'New component type',
    'Neuer Komponententyp',
    'Type du nouveau composant',
    'Tipo nuovo componente',
  ],
  增加组件: [
    'Add component',
    'Komponente hinzufügen',
    'Ajouter un composant',
    'Aggiungi componente',
  ],
  复制组件: [
    'Duplicate component',
    'Komponente duplizieren',
    'Dupliquer le composant',
    'Duplica componente',
  ],
  增加挂点: [
    'Add socket',
    'Befestigungspunkt hinzufügen',
    'Ajouter une fixation',
    'Aggiungi aggancio',
  ],
  增加安装锚点: [
    'Add attachment anchor',
    'Montageanker hinzufügen',
    'Ajouter une ancre de montage',
    'Aggiungi ancora di montaggio',
  ],
  删除选中组件或挂点: [
    'Delete selected component or socket',
    'Auswahl löschen',
    'Supprimer la sélection',
    'Elimina selezione',
  ],
  组件名称: ['Component name', 'Komponentenname', 'Nom du composant', 'Nome componente'],
  挂点名称: ['Socket name', 'Name des Befestigungspunkts', 'Nom de fixation', 'Nome aggancio'],
  父组件: ['Parent component', 'Übergeordnete Komponente', 'Composant parent', 'Componente padre'],
  拖动位置: ['Drag position', 'Position verschieben', 'Déplacer la position', 'Trascina posizione'],
  拖动方向: ['Drag rotation', 'Ausrichtung drehen', 'Modifier la rotation', 'Trascina rotazione'],
  '位置（米）': ['Position (m)', 'Position (m)', 'Position (m)', 'Posizione (m)'],
  '方向（度）': ['Rotation (degrees)', 'Drehung (Grad)', 'Rotation (degrés)', 'Rotazione (gradi)'],
  缩放: ['Scale', 'Skalierung', 'Échelle', 'Scala'],
  允许挂载的部件版本: [
    'Allowed attachment versions',
    'Zulässige Anbauteilversionen',
    'Versions d’accessoires autorisées',
    'Versioni componenti consentite',
  ],
  装配预览: [
    'Assembly preview',
    'Montagevorschau',
    'Aperçu d’assemblage',
    'Anteprima assemblaggio',
  ],
  空: ['Empty', 'Leer', 'Vide', 'Vuoto'],
  'AMC 原始字段与依赖': [
    'AMC fields and dependencies',
    'AMC-Felder und Abhängigkeiten',
    'Champs AMC et dépendances',
    'Campi AMC e dipendenze',
  ],
  '保留气动、质量、控制等原始数据；本页生成三维几何，不运行性能求解。': [
    'Aerodynamic, mass and control data are preserved. This page generates 3D geometry; it does not run performance solvers.',
    'Aerodynamik-, Massen- und Steuerungsdaten bleiben erhalten. Diese Seite erzeugt 3D-Geometrie ohne Leistungsberechnung.',
    'Les données aérodynamiques, de masse et de contrôle sont conservées. Cette page génère la géométrie 3D sans calcul de performances.',
    'Dati aerodinamici, di massa e controllo conservati. Questa pagina genera geometria 3D senza calcoli di prestazioni.',
  ],
  'JSON 参数': ['JSON parameters', 'JSON-Parameter', 'Paramètres JSON', 'Parametri JSON'],
  'JSON 格式无效': ['Invalid JSON', 'Ungültiges JSON', 'JSON invalide', 'JSON non valido'],
  应用参数: [
    'Apply parameters',
    'Parameter anwenden',
    'Appliquer les paramètres',
    'Applica parametri',
  ],
  '打开浏览器 Mover Creator': [
    'Open browser Mover Creator',
    'Mover Creator im Browser öffnen',
    'Ouvrir Mover Creator dans le navigateur',
    'Apri Mover Creator nel browser',
  ],
  '编辑挂点 / 派生模型': [
    'Edit sockets / derive model',
    'Befestigung bearbeiten / Modell ableiten',
    'Modifier les fixations / dériver le modèle',
    'Modifica agganci / deriva modello',
  ],
  '三维画布已中断，请重新生成预览': [
    '3D context interrupted. Regenerate the preview.',
    '3D-Kontext unterbrochen. Vorschau neu erzeugen.',
    'Contexte 3D interrompu. Régénérez l’aperçu.',
    'Contesto 3D interrotto. Rigenerare l’anteprima.',
  ],
  'Mover 三维画布，拖动旋转，滚轮缩放': [
    'Mover 3D canvas: drag to orbit, scroll to zoom',
    'Mover 3D: Ziehen zum Drehen, Mausrad zum Zoomen',
    'Vue 3D Mover : glisser pour tourner, défiler pour zoomer',
    'Vista 3D Mover: trascina per ruotare, scorri per ingrandire',
  ],
};
export function moverText(language: string, text: string) {
  const index = ['en', 'de', 'fr', 'it'].indexOf(language);
  return index < 0 ? text : (rows[text]?.[index] ?? text);
}
export function useMoverText() {
  const language = usePreferencesStore((s) => s.language);
  return useCallback((text: string) => moverText(language, text), [language]);
}
