import { strToU8, zipSync } from 'fflate';
import type { MapDocument, MapFeature, Layer } from '../model';
import { parseSidc } from '../symbology';

/** AFSIM 想定导出选项。未传 layerIds 时导出文档中的全部图层。 */
export interface AfsimExportOptions {
  /** 导出的项目名称；同时作为 .afproj 文件名。 */
  name?: string;
  /** 只导出指定图层。空数组表示导出空想定。 */
  layerIds?: readonly string[];
}

export interface AfsimExportFile {
  path: string;
  content: string;
}

export interface AfsimExportResult {
  /** 按标准 AFSIM 目录层级打包的 ZIP。 */
  archive: Uint8Array;
  /** ZIP 中的文本文件，便于预览、审计和无损测试。 */
  files: readonly AfsimExportFile[];
  /** AFSIM 入口文件。 */
  entry: 'main.txt';
  /** 成功写入的静态 platform 数量。 */
  exported: number;
  /** 因无静态点坐标或不支持的要素而跳过的数量。 */
  skipped: number;
  /** 面向用户的兼容性诊断。 */
  warnings: readonly string[];
}

const MAX_NAME_LENGTH = 48;

/** 使用户输入成为跨平台且不会改变 AFSIM 词法的文件/标识符。 */
function safeName(value: string, fallback: string): string {
  const normalized = value
    .normalize('NFKC')
    .replace(/[^A-Za-z0-9_\-\u0080-\uffff]+/g, '_')
    .replace(/^[_\-.]+|[_\-.]+$/g, '')
    .slice(0, MAX_NAME_LENGTH);
  return normalized || fallback;
}

function uniqueName(value: string, used: Set<string>): string {
  const base = safeName(value, 'unit');
  let name = base;
  let index = 2;
  while (used.has(name.toLowerCase())) name = `${base}_${index++}`;
  used.add(name.toLowerCase());
  return name;
}

function layerFileName(layer: Layer, used: Set<string>): string {
  const preferred = layer.group?.trim() || layer.name;
  const base = safeName(preferred, `layer_${layer.order + 1}`);
  let value = base;
  let index = 2;
  while (used.has(value.toLowerCase())) value = `${base}_${index++}`;
  used.add(value.toLowerCase());
  return value;
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/[\r\n]/g, ' ')}"`;
}

function finiteCoordinate(feature: MapFeature): { lat: number; lon: number } | null {
  if (feature.geometry.kind !== 'point') return null;
  const { lat, lon } = feature.geometry.position;
  return Number.isFinite(lat) && Number.isFinite(lon) && Math.abs(lat) <= 90 && Math.abs(lon) <= 180
    ? { lat, lon }
    : null;
}

function sideOf(layer: Layer, feature: MapFeature): string {
  const group = (layer.group ?? '').trim().toLowerCase();
  if (group === 'blue' || group === 'red' || group === 'neutral' || group === 'friendly')
    return group === 'friendly' ? 'blue' : group;
  try {
    const affiliation = parseSidc(feature.sidc).affiliation;
    return affiliation === 3 ? 'blue' : affiliation === 6 ? 'red' : affiliation === 4 ? 'neutral' : 'unknown';
  } catch {
    return 'unknown';
  }
}

function domainOf(feature: MapFeature): string {
  try {
    const symbolSet = parseSidc(feature.sidc).symbolSet;
    if (symbolSet === 1 || symbolSet === 2) return 'air';
    if (symbolSet === 30 || symbolSet === 36) return 'surface';
    if (symbolSet === 35) return 'subsurface';
    if (symbolSet === 5 || symbolSet === 6) return 'space';
  } catch {
    /* 非标准内部 SIDC 使用陆上静态平台作为安全默认值。 */
  }
  return 'land';
}

function altitudeLine(feature: MapFeature): string | null {
  const value = feature.textFields.altitudeDepth?.trim();
  if (!value) return null;
  const match = /^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s*(m|km|ft|feet|yd|mi|nm)?(?:\s+(?:agl|msl))?$/i.exec(value);
  if (!match) return null;
  const amount = Number(match[1]);
  if (!Number.isFinite(amount)) return null;
  const unit = (match[2] ?? 'm').toLowerCase().replace('feet', 'ft');
  return `  altitude ${amount} ${unit}`;
}

function platformText(feature: MapFeature, layer: Layer, name: string): string {
  const point = finiteCoordinate(feature)!;
  const lines = [
    `# Generated by map.army AFSIM exporter; source layer: ${layer.name}`,
    `# Source name: ${feature.name || name}`,
    `platform ${name} WSF_PLATFORM`,
    `  side ${sideOf(layer, feature)}`,
    `  spatial_domain ${domainOf(feature)}`,
    `  icon MAP_ARMY_UNIT`,
    `  marking ${quote(feature.name || name)}`,
    `  position ${point.lat} ${point.lon}`,
  ];
  if (feature.direction !== undefined && Number.isFinite(feature.direction)) {
    const heading = ((feature.direction % 360) + 360) % 360;
    lines.push(`  heading ${heading} deg`);
  }
  const altitude = altitudeLine(feature);
  if (altitude) lines.push(altitude);
  lines.push('end_platform', '');
  return lines.join('\n');
}

function projectFile(name: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>\n<wsf-ide-project-file>\n <wsf-ide-project project-directory="">\n  <wsf-ide-scenario command-line-args="$(SCENARIO_FILES)" working-directory="">\n   <file-item file-path="main.txt" file-type="file-main-source"/>\n  </wsf-ide-scenario>\n </wsf-ide-project>\n</wsf-ide-project-file>\n`;
}

function readme(name: string, exported: number, skipped: number): string {
  return [
    `# ${name}`,
    '',
    '此目录由 map.army 导出，入口为 `main.txt`。平台文件位于 `platforms/`，可在 AFSIM/Wizard 中作为普通想定打开。',
    '',
    `静态平台：${exported}；跳过要素：${skipped}。`,
    '仅点军标可以转换为 AFSIM platform；折线、面和缺少有效 WGS84 点坐标的要素需要在 AFSIM 中另行建模。',
    '导出器不会执行脚本、生成轨道或复制仿真组件库；平台统一使用 WSF_PLATFORM 和 MAP_ARMY_UNIT 图标。',
    '',
  ].join('\n');
}

/** 将地图文档转换为标准 AFSIM 文本目录并返回 ZIP。 */
export function documentToAfsim(
  document: MapDocument,
  options: AfsimExportOptions = {},
): AfsimExportResult {
  const projectName = safeName(options.name ?? document.name, 'map_army_scenario');
  const selected = options.layerIds ? new Set(options.layerIds) : null;
  const layers = document.layers
    .filter((layer) => !selected || selected.has(layer.id))
    .sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  const warnings: string[] = [];
  let exported = 0;
  let skipped = 0;
  const usedPlatformNames = new Set<string>();
  const usedLayerNames = new Set<string>();
  const platformFiles: AfsimExportFile[] = [];
  const includes: string[] = [];

  for (const layer of layers) {
    const features = document.features.filter((feature) => feature.layerId === layer.id);
    const layerName = layerFileName(layer, usedLayerNames);
    const rows: string[] = [];
    for (const feature of features) {
      const point = finiteCoordinate(feature);
      if (!point) {
        skipped++;
        warnings.push(
          `${feature.name || feature.id}：仅支持带有效 WGS84 点坐标的军标，已跳过 ${feature.geometry.kind} 要素`,
        );
        continue;
      }
      const name = uniqueName(feature.name || `unit_${exported + 1}`, usedPlatformNames);
      rows.push(platformText(feature, layer, name));
      exported++;
    }
    const path = `platforms/${layerName}.txt`;
    platformFiles.push({
      path,
      content:
        rows.join('\n') ||
        `# Layer ${layer.name} contains no static point platforms exportable to AFSIM.\n`,
    });
    includes.push(`include_once ${path}`);
  }

  const main = [
    '# Generated by map.army. Open this file as the AFSIM scenario entry.',
    ...includes,
    '',
    'end_time 1 sec',
    '',
  ].join('\n');
  const files: AfsimExportFile[] = [
    { path: 'main.txt', content: main },
    ...platformFiles,
    { path: `${projectName}.afproj`, content: projectFile(projectName) },
    { path: 'README.txt', content: readme(projectName, exported, skipped) },
  ];
  const archive = zipSync(
    Object.fromEntries(files.map((file) => [file.path, strToU8(file.content)])),
  );
  return { archive, files, entry: 'main.txt', exported, skipped, warnings };
}

/** 便捷导出入口，供下载按钮直接取得 ZIP 字节。 */
export function exportAfsimArchive(
  document: MapDocument,
  options: AfsimExportOptions = {},
): Uint8Array {
  return documentToAfsim(document, options).archive;
}
