/** 三维详情新增文案覆盖现有五种界面语言；键同时作为中文回退文案。 */
const messages: Record<string, readonly [string, string, string, string]> = {
  三维模型: ['3D model', '3D-Modell', 'Modèle 3D', 'Modello 3D'],
  '正在加载三维组件…': [
    'Loading 3D viewer…',
    '3D-Ansicht wird geladen…',
    'Chargement de la vue 3D…',
    'Caricamento vista 3D…',
  ],
  '线、面和控制措施不对应单台装备模型。': [
    'Lines, areas and control measures do not represent individual equipment.',
    'Linien, Flächen und Kontrollmaßnahmen stellen keine einzelnen Geräte dar.',
    'Les lignes, zones et mesures de contrôle ne représentent pas un équipement individuel.',
    'Linee, aree e misure di controllo non rappresentano singoli mezzi.',
  ],
  '此军标尚未关联三维模型。': [
    'No 3D model is linked to this symbol.',
    'Mit diesem Symbol ist kein 3D-Modell verknüpft.',
    'Aucun modèle 3D associé à ce symbole.',
    'Nessun modello 3D associato a questo simbolo.',
  ],
  '可关联通用飞机验证旋转、缩放和挂载。当前资产为类别示意，不代表具体型号。': [
    'Link a generic aircraft to explore rotation, zoom and attachments. This schematic does not represent a specific aircraft type.',
    'Verknüpfen Sie ein generisches Flugzeug für Rotation, Zoom und Anbauteile. Die Darstellung zeigt keinen bestimmten Flugzeugtyp.',
    'Associez un avion générique pour explorer rotation, zoom et accessoires. Ce schéma ne représente pas un type précis.',
    'Associa un aereo generico per esplorare rotazione, zoom e accessori. Lo schema non rappresenta un tipo specifico.',
  ],
  关联示意飞机: [
    'Link schematic aircraft',
    'Schematisches Flugzeug verknüpfen',
    'Associer un avion schématique',
    'Associa aereo schematico',
  ],
  '通用飞机（类别示意）': [
    'Generic aircraft (schematic)',
    'Generisches Flugzeug (Schema)',
    'Avion générique (schéma)',
    'Aereo generico (schema)',
  ],
  '类别示意 · 三维装配为本项目扩展': [
    'Schematic · 3D assembly is a project extension',
    'Schema · 3D-Montage ist eine Projekterweiterung',
    'Schéma · Assemblage 3D propre au projet',
    'Schema · Assemblaggio 3D specifico del progetto',
  ],
  移除模型与所有挂载: [
    'Remove model and all attachments',
    'Modell und alle Anbauteile entfernen',
    'Retirer le modèle et tous les accessoires',
    'Rimuovi modello e tutti gli accessori',
  ],
  '装配随文档保存，可撤销。真实装备型号仍需另行建模和关联。': [
    'Assembly is saved with the document and supports undo. Actual equipment types need separate models and links.',
    'Die Montage wird im Dokument gespeichert und ist rückgängig machbar. Reale Gerätetypen benötigen eigene Modelle und Verknüpfungen.',
    'L’assemblage est enregistré dans le document et peut être annulé. Les équipements réels nécessitent leurs propres modèles.',
    'L’assemblaggio è salvato nel documento ed è annullabile. I mezzi reali richiedono modelli e associazioni dedicati.',
  ],
  '装配数据格式无效。': [
    'Invalid assembly data.',
    'Ungültige Montagedaten.',
    'Données d’assemblage invalides.',
    'Dati di assemblaggio non validi.',
  ],
  '当前部署没有此模型版本；已保留原装配数据。': [
    'This model version is unavailable here; the original assembly data is preserved.',
    'Diese Modellversion ist hier nicht verfügbar; die ursprünglichen Montagedaten bleiben erhalten.',
    'Cette version du modèle est indisponible ; les données d’assemblage sont conservées.',
    'Questa versione del modello non è disponibile; i dati originali sono conservati.',
  ],
  '当前部署无法解析部分挂载；已保留原装配数据。': [
    'Some attachments are unavailable here; the original assembly data is preserved.',
    'Einige Anbauteile sind hier nicht verfügbar; die ursprünglichen Montagedaten bleiben erhalten.',
    'Certains accessoires sont indisponibles ; les données d’assemblage sont conservées.',
    'Alcuni accessori non sono disponibili; i dati originali sono conservati.',
  ],
  '此浏览器无法创建三维画布，请启用 WebGL 后重试。': [
    'Unable to create a 3D canvas. Enable WebGL and retry.',
    '3D-Ansicht nicht verfügbar. WebGL aktivieren und erneut versuchen.',
    'Impossible de créer la vue 3D. Activez WebGL et réessayez.',
    'Impossibile creare la vista 3D. Attiva WebGL e riprova.',
  ],
  '三维画布已中断，请重新加载模型。': [
    'The 3D canvas was interrupted. Reload the model.',
    'Die 3D-Ansicht wurde unterbrochen. Modell erneut laden.',
    'La vue 3D a été interrompue. Rechargez le modèle.',
    'La vista 3D è stata interrotta. Ricarica il modello.',
  ],
  '模型加载失败，请检查网络后重试。': [
    'Model loading failed. Check the connection and retry.',
    'Modell konnte nicht geladen werden. Verbindung prüfen und erneut versuchen.',
    'Échec du chargement. Vérifiez la connexion et réessayez.',
    'Caricamento fallito. Verifica la connessione e riprova.',
  ],
  '模型挂点数据无效。': [
    'Invalid model mount data.',
    'Ungültige Befestigungsdaten.',
    'Points de fixation invalides.',
    'Dati dei punti di attacco non validi.',
  ],
  '模型挂点与资产目录不一致。': [
    'Model mounts do not match the asset catalog.',
    'Befestigungen stimmen nicht mit dem Modellkatalog überein.',
    'Les fixations ne correspondent pas au catalogue.',
    'I punti di attacco non corrispondono al catalogo.',
  ],
  '部件缺少安装锚点。': [
    'Attachment has no mounting anchor.',
    'Dem Anbauteil fehlt ein Montageanker.',
    'L’accessoire ne possède pas d’ancrage.',
    'L’accessorio non ha un ancoraggio.',
  ],
  '模型无法显示。': [
    'Unable to display model.',
    'Modell kann nicht angezeigt werden.',
    'Impossible d’afficher le modèle.',
    'Impossibile visualizzare il modello.',
  ],
  '挂载已安装，可撤销。': [
    'Attachment installed. Undo is available.',
    'Anbauteil montiert. Rückgängig möglich.',
    'Accessoire installé. Annulation possible.',
    'Accessorio installato. È possibile annullare.',
  ],
  '挂载已拆卸，可撤销。': [
    'Attachment removed. Undo is available.',
    'Anbauteil entfernt. Rückgängig möglich.',
    'Accessoire retiré. Annulation possible.',
    'Accessorio rimosso. È possibile annullare.',
  ],
  '正在加载三维模型…': [
    'Loading 3D model…',
    '3D-Modell wird geladen…',
    'Chargement du modèle 3D…',
    'Caricamento modello 3D…',
  ],
  重新加载模型: ['Reload model', 'Modell erneut laden', 'Recharger le modèle', 'Ricarica modello'],
  重置视角: ['Reset view', 'Ansicht zurücksetzen', 'Réinitialiser la vue', 'Ripristina vista'],
  查看机腹: ['View underside', 'Unterseite anzeigen', 'Voir le dessous', 'Mostra parte inferiore'],
  '拖动模型旋转，滚轮或双指缩放。': [
    'Drag to rotate; use the wheel or pinch to zoom. ',
    'Ziehen zum Drehen; Mausrad oder zwei Finger zum Zoomen. ',
    'Glissez pour tourner ; molette ou pincement pour zoomer. ',
    'Trascina per ruotare; rotella o due dita per lo zoom. ',
  ],
  '当前只读，可自由查看模型。': [
    'Read only. You can still explore the model.',
    'Schreibgeschützt. Das Modell kann weiter betrachtet werden.',
    'Lecture seule. Vous pouvez explorer le modèle.',
    'Sola lettura. Puoi esplorare il modello.',
  ],
  '拖动部件到绿色挂点，或选择部件后点击挂点安装；Esc 取消拖动。': [
    'Drag a part onto a green mount, or select a part then click a mount. Esc cancels dragging.',
    'Teil auf eine grüne Befestigung ziehen oder Teil wählen und Befestigung anklicken. Esc bricht ab.',
    'Glissez un accessoire sur une fixation verte, ou sélectionnez-le puis cliquez sur une fixation. Échap annule.',
    'Trascina un accessorio su un attacco verde, oppure selezionalo e tocca un attacco. Esc annulla.',
  ],
  点击或拖入所选部件: [
    'Click or drop the selected part',
    'Klicken oder ausgewähltes Teil ablegen',
    'Cliquez ou déposez l’accessoire choisi',
    'Fai clic o rilascia l’accessorio scelto',
  ],
  此挂点不接受所选部件: [
    'This mount does not accept the selected part',
    'Diese Befestigung ist nicht kompatibel',
    'Cette fixation est incompatible',
    'Questo attacco non è compatibile',
  ],
  '副油箱（示意）': [
    'Fuel tank (schematic)',
    'Zusatztank (Schema)',
    'Réservoir (schéma)',
    'Serbatoio (schema)',
  ],
  '传感器吊舱（示意）': [
    'Sensor pod (schematic)',
    'Sensorbehälter (Schema)',
    'Nacelle capteur (schéma)',
    'Pod sensore (schema)',
  ],
  左翼: ['Left wing', 'Linker Flügel', 'Aile gauche', 'Ala sinistra'],
  右翼: ['Right wing', 'Rechter Flügel', 'Aile droite', 'Ala destra'],
  机腹: ['Underside', 'Unterseite', 'Dessous', 'Parte inferiore'],
  空: ['Empty', 'Leer', 'Vide', 'Vuoto'],
  挂点: [' mount', ' – Befestigung', ' – fixation', ' – attacco'],
  挂载: [' attachment', ' – Anbauteil', ' – accessoire', ' – accessorio'],
  拆卸: ['Remove ', 'Entfernen: ', 'Retirer ', 'Rimuovi '],
  安装: ['Install', 'Montieren', 'Installer', 'Installa'],
  安装到: ['Install on ', 'Montieren an: ', 'Installer sur ', 'Installa su '],
  可挂载部件: [
    'Available attachments',
    'Verfügbare Anbauteile',
    'Accessoires disponibles',
    'Accessori disponibili',
  ],
  当前装配: ['Current assembly', 'Aktuelle Montage', 'Assemblage actuel', 'Assemblaggio attuale'],
  '三维装配示意：机翼支持两类部件，机腹支持传感器。': [
    'Schematic assembly: wings accept both parts; the underside accepts the sensor.',
    'Schematische Montage: Flügel erlauben beide Teile, die Unterseite den Sensor.',
    'Assemblage schématique : les ailes acceptent les deux accessoires, le dessous accepte le capteur.',
    'Assemblaggio schematico: le ali accettano entrambi gli accessori, la parte inferiore il sensore.',
  ],
  '三维装备预览，拖动旋转、滚轮缩放': [
    '3D equipment preview. Drag to rotate, wheel to zoom.',
    '3D-Gerätevorschau. Ziehen zum Drehen, Mausrad zum Zoomen.',
    'Aperçu 3D. Glissez pour tourner, molette pour zoomer.',
    'Anteprima 3D. Trascina per ruotare, rotella per lo zoom.',
  ],
  '三维模型与挂载仅保存在本项目私有扩展中，原站及其他 MilX 软件不显示装配。': [
    '3D models and attachments are stored in a project extension; the original site and other MilX software do not display the assembly.',
    '3D-Modelle und Anbauteile werden in einer Projekterweiterung gespeichert; Originalseite und andere MilX-Software zeigen die Montage nicht an.',
    'Les modèles 3D et accessoires sont enregistrés dans une extension du projet ; le site d’origine et les autres logiciels MilX n’affichent pas l’assemblage.',
    'Modelli 3D e accessori sono salvati in un’estensione del progetto; il sito originale e altri software MilX non visualizzano l’assemblaggio.',
  ],
  'KML 不保留三维装配；如需继续编辑装配，请另存项目 JSON': [
    'KML does not retain 3D assembly; save project JSON to keep editing it.',
    'KML erhält die 3D-Montage nicht; zum Weiterbearbeiten als Projekt-JSON speichern.',
    'KML ne conserve pas l’assemblage 3D ; enregistrez le projet en JSON pour le modifier.',
    'KML non conserva l’assemblaggio 3D; salva il progetto in JSON per continuare a modificarlo.',
  ],
};

/** 按偏好语言翻译三维详情文案，未知或旧版本文案原样保留。 */
export function equipmentText(language: string, message: string): string {
  const index = ['en', 'de', 'fr', 'it'].indexOf(language);
  return index < 0 ? message : (messages[message]?.[index] ?? message);
}
